FUCarRentingSystem_RazorPage/Pages/Admin/CarRentals/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using Domain;
using Domain.Entities;

namespace FUCarRentingSystem_RazorPage.Pages.Admin.CarRentals
{
    public class DeleteModel : PageModel
    {
        private readonly Domain.AppDBContext _context;

        public DeleteModel(Domain.AppDBContext context)
        {
            _context = context;
        }

        [BindProperty]
      public CarRental CarRental { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null || _context.CarRentals == null)
            {
                return NotFound();
            }

            var carrental = await _context.CarRentals.FirstOrDefaultAsync(m => m.CarId == id);

            if (carrental == null)
            {
                return NotFound();
            }
            else 
            {
                CarRental = carrental;
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null || _context.CarRentals == null)
            {
                return NotFound();
            }
            var carrental = await _context.CarRentals.FindAsync(id);

            if (carrental != null)
            {
                CarRental = carrental;
                _context.CarRentals.Remove(CarRental);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

FUCarRentingSystem_RazorPage/Pages/Admin/Cars/Create.cshtml.cs
using Domain.Entities;
using FUCarRentingSystem_RazorPage.Utils;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Reflection.Metadata;
using System.Text;
using System.Text.Json;

namespace FUCarRentingSystem_RazorPage.Pages.Admin.Cars
{
    public class CreateModel : PageModel
    {
        private readonly HttpClient _client;

        public CreateModel()
        {
            _client = new HttpClient();
            _client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public Car Car { get; set; } = default!;


        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            //prepare data
            var json = JsonSerializer.Serialize(Car);
            var stringContent = new StringContent(json, Encoding.UTF8, "application/json");
            // send data
            var response = await _client.PostAsync($"{Constants.ApiRoute.CarsApi}", stringContent);

            if (response.IsSuccessStatusCode)
            {
                return RedirectToPage("Index");
            }
            ViewData["ErrorMessage"] = await response.Content.ReadAsStringAsync();

            return Page();
        }

        public override PageResult Page()
        {
            Task task = Task.Run(async () =>
            {
                var carProducers = await _client.GetAsync<List<CarProducer>>( Constants.ApiRoute.ProducersApi);
                ViewData["Producer"] = new SelectList(carProducers, "Id", "ProducerName");
            });
            task.Wait();
            return base.Page();
        }
    }
}

FUCarRentingSystem_RazorPage/Pages/Admin/Cars/Details.cshtml.cs
using Domain.Entities;
using FUCarRentingSystem_RazorPage.Utils;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace FUCarRentingSystem_RazorPage.Pages.Admin.Cars
{
    public class DetailsModel : PageModel
    {
        private HttpClient _client;

        public DetailsModel()
        {
            _client = new HttpClient();
            _client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
        }

        public Car Car { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null) return NotFound();

            var response = await _client.GetStringAsync($"{Constants.ApiRoute.CarsApi}/{id}");
            var car = response.Deserialize<Car>();
            if (car == null)
            {
                return NotFound();
            }
            Car = car;
            return Page();
        }
        public async Task<IActionResult> OnPostDeleteAsync(int? id)
        {
            if (id == null) return NotFound();
            var response = await _client.DeleteAsync($"{Constants.ApiRoute.CarsApi}/{id}");

            if (response.IsSuccessStatusCode)
            {
                return RedirectToPage("Index");
            }
            ViewData["ErrorMessage"] = await response.Content.ReadAsStringAsync();
            return Page();
        }
    }
}

FUCarRentingSystem_RazorPage/Pages/Admin/Cars/Edit.cshtml.cs
using Domain.Entities;
using FUCarRentingSystem_RazorPage.Utils;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Text;
using System.Text.Json;

namespace FUCarRentingSystem_RazorPage.Pages.Admin.Cars
{
    public class EditModel : PageModel
    {
        private readonly HttpClient _client;

        public EditModel()
        {
            _client = new HttpClient();
            _client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
        }

        [BindProperty]
        public Car Car { get; set; } = default!;

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null) return NotFound();

            var response = await _client.GetStringAsync($"{Constants.ApiRoute.CarsApi}/{id}");
            var car = response.Deserialize<Car>();
            if (car == null)
            {
                return NotFound();
            }
            Car = car;
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            //prepare data
            var json = JsonSerializer.Serialize(Car);
            var stringContent = new StringContent(json, Encoding.UTF8, "application/json");
            // send data
            var response = await _client.PutAsync($"{Constants.ApiRoute.CarsApi}/{Car.Id}", stringContent);

            if (response.IsSuccessStatusCode) {
                return RedirectToPage("Index");
            }

            ViewData["ErrorMessage"] = await response.Content.ReadAsStringAsync();
            return Page();
        }
        public override PageResult Page()
        {
            Task task = Task.Run(async () =>
            {
                var carProducers = await _client.GetAsync<List<CarProducer>>(Constants.ApiRoute.ProducersApi);
                ViewData["Producer"] = new SelectList(carProducers, "Id", "ProducerName");
            });
            task.Wait();
            return base.Page();
        }

    }
}

FUCarRentingSystem_RazorPage/Pages/Admin/Customers/Create.cshtml.cs
using Domain.Entities;
using FUCarRentingSystem_RazorPage.Utils;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Text;
using System.Text.Json;

namespace FUCarRentingSystem_RazorPage.Pages.Admin.Customers
{
    public class CreateModel : PageModel
    {
        private readonly HttpClient _client;

        public CreateModel()
        {
            _client = new HttpClient();
            _client.DefaultRequestHeaders.Accept.Add(new System.Net.Http.Headers.MediaTypeWithQualityHeaderValue("application/json"));
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public Customer Customer { get; set; } = default!;


        // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }
            //prepare data
            var json = JsonSerializer.Serialize(Customer);
            var stringContent = new StringContent(json, Encoding.UTF8, "application/json");
            // send data
            var response = await _client.PostAsync($"{Constants.ApiRoute.CustomersApi}", stringContent);
            if (response.IsSuccessStatusCode)
            {
                return RedirectToPage("Index");
            }
            ViewData["ErrorMessage"] = await response.Content.ReadAsStringAsync();
            return Page();
        }
    }
}

FUCarRentingSystem_RazorPage/Pages/Admin/Transaction/CarList.cshtml.cs
using Domain.Entities;
using DTOS.DTOS;
using FUCarRentingSystem_RazorPage.Utils;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using OData.QueryBuilder.Builders;
using System.Net.Http.Headers;

namespace FUCarRentingSystem_RazorPage.Pages.Admin.Transaction
{
    public class CarListModel : PageModel
    {
        private readonly HttpClient _client;

        public CarListModel()
        {
            _client = new HttpClient();
            _client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
            PageUri = Constants.ApiRoute.CarsApi;
        }


        public IList<Car>? Cars { get; set; } = default!;
        [BindProperty(SupportsGet = true)]
        public int? CustomerId { get; set; } = default!;
        [BindProperty(SupportsGet = true)]
        public CarRentalDTO? CarRental { get; set; }
        public string PageUri { get; }

        public async Task<IActionResult> OnGetAsync()
        {
            CarRental ??= HttpContext.Session.GetString($"RentCar")?.Deserialize<CarRentalDTO>() ?? new CarRentalDTO
            {
                PickupDate = DateTime.Today,
                ReturnDate = DateTime.Today,
                CarId = null,
            };
            Cars = await _client.GetAsync<List<Car>>($"{PageUri}?$filter=status eq true&expand=carrentals($filter=status eq true),producer");
            var uri = new ODataQueryBuilder(Constants.ApiRoute.DefaultPath, new OData.QueryBuilder.Options.ODataQueryBuilderOptions
            {
                UseCorrectDateTimeFormat = true
            }).For<CarRental>("CarRentals")
                                                    .ByList()
                                                    .Filter((s, f, o) => s.Status == true
                                                                         && (f.Date(s.PickupDate) <= CarRental.PickupDate
                                                                         && f.Date(s.ReturnDate) >= CarRental.PickupDate
                                                                         || f.Date(s.ReturnDate) >= CarRental.ReturnDate
                                                                         && f.Date(s.ReturnDate) >= CarRental.ReturnDate))
                                                    .Expand(x=>x.Car).Expand(x=>x.Customer)
                                                    .ToUri();
            CarRental.UpdateRentPrice(Cars?.FirstOrDefault(x => x.Id == CarRental.CarId)?.RentPrice ?? 0);
            List<CarRental>? carRentals = await _client.GetAsync<List<CarRental>>(uri.ToString());
            if (Cars?.Count > 0 && carRentals?.Count > 0)
            {
                var removeList = new List<Car>();
                foreach (var car in Cars)
                {
                    if (carRentals.Any(x => x.CarId == car.Id)) removeList.Add(car);
                }
                removeList.ForEach(x => Cars.Remove(x));
            }
            HttpContext.Session.SetInt32($"RentCarCusID", CustomerId.Value);
            HttpContext.Session.SetString($"RentCar", CarRental.Serialize());
            return Page();
        }

        public async Task<IActionResult> OnPostRent(int id)
        {
            var response = await _client.GetAsync($"{PageUri}/{id}");
            if (!response.IsSuccessStatusCode)
            {
                return RedirectToAction("", new { CarRental });
            }
            string strdata = await response.Content.ReadAsStringAsync();
            var car = strdata.Deserialize<Car>();
            if (car != null)
            {
                CarRental.CarId = id;
                CarRental.UpdateRentPrice(car.RentPrice);
            }
            HttpContext.Session.SetInt32($"RentCarCusID", CustomerId.Value);
            HttpContext.Session.SetString($"RentCar", CarRental.Serialize());
            return RedirectToPage("./Create");
        }

    }
}

FUCarRentingSystem_RazorPage/Pages/Admin/Transaction/CarListEdit.cshtml.cs
using Domain.Entities;
using DTOS.DTOS;
using FUCarRentingSystem_RazorPage.Utils;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using OData.QueryBuilder.Builders;
using System.Net.Http.Headers;

namespace FUCarRentingSystem_RazorPage.Pages.Admin.Transaction
{
    public class CarListModelEdit : PageModel
    {
        private readonly HttpClient _client;

        public CarListModelEdit()
        {
            _client = new HttpClient();
            _client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
            PageUri = Constants.ApiRoute.CarsApi;
        }


        public IList<Car>? Cars { get; set; } = default!;
        [BindProperty(SupportsGet = true)]
        public CarRentalDTO? CarRental { get; set; }
        [BindProperty(SupportsGet = true)]
        public int? CustomerId { get; set; }
        public string PageUri { get; }
        private string Key { get; set; } = default!;

        public async Task<IActionResult> OnPostSelectAsync(int carId, int customerId, string date)
        {
            Key = $"RentCar{carId}{customerId}{date}";
            CarRental ??= HttpContext.Session.GetString(Key)?.Deserialize<CarRentalDTO>() ?? new CarRentalDTO
            {
                PickupDate = DateTime.Today,
                ReturnDate = DateTime.Today,
                CarId = null,
            };
            Cars = await _client.GetAsync<List<Car>>($"{PageUri}?$filter=status eq true&expand=carrentals($filter=status eq true),producer");
            var uri = new ODataQueryBuilder(Constants.ApiRoute.DefaultPath, new OData.QueryBuilder.Options.ODataQueryBuilderOptions
            {
                UseCorrectDateTimeFormat = true
            }).For<CarRental>("CarRentals")
                                                    .ByList()
                                                    .Filter((s, f, o) => s.Status == true
                                                                         && (f.Date(s.PickupDate) <= CarRental.PickupDate
                                                                         && f.Date(s.ReturnDate) >= CarRental.PickupDate
                                                                         || f.Date(s.ReturnDate) >= CarRental.ReturnDate
                                                                         && f.Date(s.ReturnDate) >= CarRental.ReturnDate))
                                                    .Expand(x=>x.Car).Expand(x=>x.Customer)
                                                    .ToUri();
            CarRental.UpdateRentPrice(Cars?.FirstOrDefault(x => x.Id == CarRental.CarId)?.RentPrice ?? 0);
            List<CarRental>? carRentals = await _client.GetAsync<List<CarRental>>(uri.ToString());
            if (Cars?.Count > 0 && carRentals?.Count > 0)
            {
                var removeList = new List<Car>();
                foreach (var car in Cars)
                {
                    if (carRentals.Any(x => x.CarId == car.Id) && car.Id != carId) removeList.Add(car);
                }
                removeList.ForEach(x => Cars.Remove(x));
            }

            HttpContext.Session.SetInt32($"{Key}CusID", CustomerId.Value);
            HttpContext.Session.SetString(Key, CarRental.Serialize());
            return Page();
        }

        public async Task<IActionResult> OnPostRent(int id, int carId, int customerId, string date)
        {
            Key = $"RentCar{carId}{customerId}{date}";

            var response = await _client.GetAsync($"{PageUri}/{id}");
            if (!response.IsSuccessStatusCode)
            {
                return RedirectToAction("", new { CarRental, carId, customerId, date });
            }
            string strdata = await response.Content.ReadAsStringAsync();
            var car = strdata.Deserialize<Car>();
            if (car != null)
            {
                CarRental.CarId = id;
                CarRental.UpdateRentPrice(car.RentPrice);
            }
            HttpContext.Session.SetInt32($"{Key}CusID", CustomerId.Value);
            HttpContext.Session.SetString(Key, CarRental.Serialize());
            return RedirectToPage("./Edit", new { carId, customerId, date });
        }

    }
}

FUCarRentingSystem_RazorPage/Pages/Admin/Transaction/CarList.cshtml
@page
@model             CarListModel

@{
    ViewData["Title"] = "CarList";
}

<h1>Car Renting List</h1>
<form class="d-none" id="rent-form" method="post">
    <input type="hidden" asp-for="CustomerId" />
    <input type="hidden" asp-for="CarRental.CarId" />
    <input type="hidden" asp-for="CarRental.PickupDate" />
    <input type="hidden" asp-for="CarRental.ReturnDate" />
    <input type="hidden" asp-for="CarRental.RentPrice" />
</form>
<div class="card">
    <div class="card-body">
        <label class="d-inline" asp-for="CustomerId"></label>:
        <span>@Html.DisplayFor(m=>m.CustomerId)</span>
        <br></br><label class="d-inline" asp-for="CarRental.CarId"></label>:
        <span>@Html.DisplayFor(m=>m.CarRental.CarId)</span>
        <br></br>
        <label class="d-inline" asp-for="CarRental.PickupDate"></label>:
        <span>@Html.DisplayFor(m=>m.CarRental.PickupDate)</span>
        <br></br>
        <label class="d-inline" asp-for="CarRental.ReturnDate"></label>:
        <span>@Html.DisplayFor(m=>m.CarRental.ReturnDate)</span>
        <br></br>
        <label class="d-inline" asp-for="CarRental.RentPrice"></label>:
        <span>@Html.DisplayFor(m=>m.CarRental.RentPrice)</span>
    </div>
</div>

@if (Model.Cars.Count > 0)
{
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Cars[0].CarName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Cars[0].CarModelYear)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Cars[0].Color)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Cars[0].Capacity)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Cars[0].Description)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Cars[0].ImportDate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Cars[0].RentPrice)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Cars[0].Producer)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Cars)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.CarName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CarModelYear)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Color)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Capacity)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Description)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ImportDate)
                    </td>
                    <td>
                        @{
                            dynamic days = 0;
                            try
                            {
                                days = (Model.CarRental?.ReturnDate - Model.CarRental?.PickupDate).Value.Days + 1;
                            }
                            catch
                            {

                            }
                        }
                        <div class="d-flex gap-2">
                            <div>@Html.DisplayFor(modelItem => item.RentPrice)</div>
                            <div>x </div>
                            <div>@(days)</div>
                        </div>
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Producer.ProducerName)
                    </td>
                    <td>
                        <button class="btn btn-primary" form="rent-form" asp-page="CarList"
                                asp-page-handler="Rent" asp-route-id="@item.Id">
                            Rent
                        </button>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <h3>No Car For Rent</h3>
}
<a class="" asp-page="Create">Go Back..</a>

FUCarRentingSystem_RazorPage/Pages/Admin/Transaction/CarListEdit.cshtml
@page "{carId},{customerId},{date}"
@model CarListModelEdit
@{
    ViewData["Title"] = "CarList";
}

<h1>Car Renting List For Editing</h1>
<form class="d-none" id="rent-form" method="post"
      asp-route-carId="@Request.RouteValues["carId"]"
      asp-route-customerId="@Request.RouteValues["customerId"]"
      asp-route-date="@Request.RouteValues["date"]">
    <input type="hidden" asp-for="CarRental.CarId" />
    <input type="hidden" asp-for="CarRental.PickupDate" />
    <input type="hidden" asp-for="CarRental.ReturnDate" />
    <input type="hidden" asp-for="CarRental.RentPrice" />
</form>
<div class="card">
    <div class="card-body">
        <label class="d-inline" asp-for="CustomerId"></label>:
        <span>@Html.DisplayFor(m=>m.CustomerId)</span>
        <br></br>
        <label class="d-inline" asp-for="CarRental.CarId"></label>:
        <span>@Html.DisplayFor(m=>m.CarRental.CarId)</span>
        <br></br>
        <label class="d-inline" asp-for="CarRental.PickupDate"></label>:
        <span>@Html.DisplayFor(m=>m.CarRental.PickupDate)</span>
        <br></br>
        <label class="d-inline" asp-for="CarRental.ReturnDate"></label>:
        <span>@Html.DisplayFor(m=>m.CarRental.ReturnDate)</span>
        <br></br>
        <label class="d-inline" asp-for="CarRental.RentPrice"></label>:
        <span>@Html.DisplayFor(m=>m.CarRental.RentPrice)</span>
    </div>
</div>

@if (Model.Cars.Count > 0)
{
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Cars[0].CarName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Cars[0].CarModelYear)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Cars[0].Color)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Cars[0].Capacity)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Cars[0].Description)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Cars[0].ImportDate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Cars[0].RentPrice)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Cars[0].Producer)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.Cars)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.CarName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.CarModelYear)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Color)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Capacity)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Description)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ImportDate)
                    </td>
                    <td>
                        @{
                            dynamic days = 0;
                            try
                            {
                                days = (Model.CarRental?.ReturnDate - Model.CarRental?.PickupDate).Value.Days + 1;
                            }
                            catch
                            {

                            }
                        }
                        <div class="d-flex gap-2">
                            <div>@Html.DisplayFor(modelItem => item.RentPrice)</div>
                            <div>x </div>
                            <div>@(days)</div>
                        </div>
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Producer.ProducerName)
                    </td>
                    <td>
                        <button class="btn btn-primary" form="rent-form" asp-page="CarListEdit"
                                asp-page-handler="Rent" asp-route-id="@item.Id">

                            Rent
                        </button>
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <h3>No Car For Rent</h3>
}
<a class="page-item" asp-page="Edit"
   asp-route-carId="@Request.RouteValues["carId"]"
   asp-route-customerId="@Request.RouteValues["customerId"]"
   asp-route-date="@Request.RouteValues["date"]">
    Go Back
</a>

FUCarRentingSystem_RazorPage/Pages/Admin/Transaction/Edit.cshtml
@page "{carId},{customerId},{date}"
@model             EditModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>CarRental</h4>
<hr />
<div class="card-body">
    <div class="col-md-4">
        <form method="post" id="edit-form"
              asp-route-carId="@Request.RouteValues["carId"]"
              asp-route-customerId="@Request.RouteValues["customerId"]"
              asp-route-date="@Request.RouteValues["date"]">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @{
                var item = Model.CarRental;
            }
            @Request.Query.FirstOrDefault(x=>x.Key == "date").Value

            <div class="form-group">
                <label class="control-label">Customer</label>
                <select class="form-control" asp-for="CustomerIdentity" asp-items="ViewBag.CustomerId"></select>
                <span asp-validation-for="CustomerIdentity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="form-label" asp-for="CarRental.CarId"></label>
                <button class="page-link" formmethod="post" asp-page-handler="Select"
                        asp-page="CarListEdit"
                        asp-route-carId="@Request.RouteValues["carId"]"
                        asp-route-customerId="@Request.RouteValues["customerId"]"
                        asp-route-date="@Request.RouteValues["date"]">
                    
                    @(Model.Car?.CarName ?? "Select Your Vehicle")
                </button>
                <input type="hidden" asp-for="CarRental.CarId" />
                <span class="text-danger my-2" asp-validation-for="CarRental.CarId"></span>
            </div>
            <div class="form-group">
                <label asp-for="CarRental.PickupDate" class="control-label"></label>
                <input asp-for="CarRental.PickupDate" class="form-control" />
                <span asp-validation-for="CarRental.PickupDate" class="text-danger"></span>
            </div>   <div class="form-group">
                <label asp-for="CarRental.ReturnDate" class="control-label"></label>
                <input asp-for="CarRental.ReturnDate" class="form-control" />
                <span asp-validation-for="CarRental.ReturnDate" class="text-danger"></span>
            </div>
            <div>
                <label class="form-label" asp-for="CarRental.RentPrice"></label>
                <input class="form-control" readonly id="inp-rent-price" asp-for="CarRental.RentPrice" />
                <span class="text-danger my-2" asp-validation-for="CarRental.RentPrice"></span>
            </div>
            <div class="text-danger">@ViewData["ErrorMessage"]</div>
        </form>
    </div>
</div>

<div class="d-flex gap-2 m-2">
    <div class="form-group">
        <input type="submit" form="edit-form" value="Save" class="btn btn-primary" />
    </div>
    <a class="page-link" asp-page="./Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}